export const packageJson = {
  name: 'openai-copilot',
  displayName: 'openai-copilot',
  description:
    'Provides live inline code completition similar to github-copilot but using openai (company that created Chat GPT)',
  version: '0.0.1',
  engines: {
    vscode: '^1.78.0',
  },
  activationEvents: ['onStartupFinished'],
  main: './dist/extension.js',
  scripts: {
    'vscode:prepublish': 'pnpm run esbuild-base -- --minify',
    'esbuild-base':
      'esbuild ./src/extension.ts --bundle --outfile=out/main.js --external:vscode --format=cjs --platform=node',
    esbuild: 'pnpm run esbuild-base -- --sourcemap',
    compile: 'tsc -p ./',
    'esbuild-watch': 'npm run esbuild-base -- --sourcemap --watch',
    watch: 'tsc -watch -p ./',
    pretest: 'pnpm run compile && pnpm run lint',
    'compile-tests': 'tsc -p . --outDir out',
    'watch-tests': 'tsc -p . -w --outDir out',
    lint: 'eslint src --ext ts',
    test: 'node ./out/test/runTest.js',
    'sync-packagejson': 'tsx  ./tools/sync-package-json.ts',
    prestart: 'pnpm sync-packagejson',
    postinstall: 'pnpm sync-packagejson',
    preversion: 'pnpm sync-packagejson',
    dependencies: 'pnpm sync-packagejson',
    prepack: 'pnpm sync-packagejson',
  },
  contributes: {
    commands: [
      {
        command: 'OpenAiCopilot::setApiToken',
        title: 'OpenAI Copilot: Set API token',
      },
      {
        command: 'OpenAiCopilot::assistantToggle',
        title: 'OpenAI Copilot: Toggle Assistant',
      },
      {
        command: 'OpenAiCopilot.hideSuggestion',
        title: 'Hide',
        icon: {
          dark: 'assets/close_inverse.svg',
          light: 'assets/close.svg',
        },
      },
      {
        command: 'OpenAiCopilot.applySuggestion',
        title: 'Apply',
        icon: {
          dark: 'assets/approve_inverse.svg',
          light: 'assets/approve.svg',
        },
      },
    ],
    configuration: [
      {
        title: 'OpenAICopilot',
        properties: {
          'OpenAI.APItoken': {
            type: ['string', 'undefined'],
            description:
              'Your Open AI API Token . please check https://platform.openai.com/account/api-keys',
          },
          'OpenAI.model': {
            type: 'string',
            default: 'gpt-3.5-turbo',
            description:
              'Model name, default is gpt-3.5-turbo . please check https://platform.openai.com/docs/models/overview',
          },
          'Others.idleToRespond': {
            type: 'number',
            default: 1.2,
            description: 'Idle time min to ask for completition',
          },
        },
      },
    ],
    keybindings: [
      {
        key: 'tab',
        command: 'ResponsiveRubberDuck.tab-override',
        when: 'OpenAiCopilot.enabled && OpenAiCopilot.haveSuggestion',
      },
      {
        key: 'tab',
        command: 'editor.action.inlineSuggest.accept',
        when: 'OpenAiCopilot.enabled && OpenAiCopilot.haveSuggestion && !editorTabMovesFocus',
      },
      {
        key: 'ctrl+z',
        mac: 'cmd+z',
        command: 'OpenAiCopilot.escape-inline-suggestion',
        when: 'OpenAiCopilot.enabled && OpenAiCopilot.haveSuggestion',
      },
      {
        key: 'alt+.',
        mac: 'cmd+.',
        command: 'OpenAiCopilot.next-inline-suggestion',
        when: 'OpenAiCopilot.enabled && OpenAiCopilot.haveSuggestion',
      },
      {
        key: 'alt+,',
        mac: 'cmd+,',
        command: 'ResponsiveOpenAiCopilotRubberDuck.prev-inline-suggestion',
        when: 'OpenAiCopilot.enabled && OpenAiCopilot.haveSuggestion',
      },
      {
        key: 'alt+.',
        mac: 'cmd+.',
        command: 'OpenAiCopilot.snippet-suggestion',
        when: 'OpenAiCopilot.enabled',
      },
    ],
  },
  devDependencies: {
    '@types/glob': '^8.1.0',
    '@types/mocha': '^10.0.1',
    '@types/node': '16.x',
    '@types/vscode': '^1.78.0',
    '@typescript-eslint/eslint-plugin': '^5.59.1',
    '@typescript-eslint/parser': '^5.59.1',
    '@vscode/test-electron': '^2.3.0',
    esbuild: '^0.17.19',
    eslint: '^8.39.0',
    'eslint-config-prettier': '^8.8.0',
    glob: '^8.1.0',
    mocha: '^10.2.0',
    prettier: '^2.8.8',
    'ts-loader': '^9.4.2',
    tsx: '^3.12.7',
    typescript: '^5.0.4',
  },
  categories: ['Programming Languages', 'Snippets', 'Other'],
  keywords: [
    'javascript',
    'python',
    'typescript',
    'php',
    'autocomplete',
    'ruby',
    'java',
    'go',
    'golang',
    'bash',
    'kotlin',
    'html',
    'css',
    'ocaml',
    'perl',
    'rust',
    'julia',
    'lua',
    'haskell',
    'c',
    'cpp',
    'c++',
    'csharp',
    'c#',
    'react',
    'swift',
    'objective-c',
    'objectivec',
    'ai',
    'method completion',
    'intellicode',
    'intellisense',
    'snippets',
    'kite',
    'nodejs',
    'node',
    'node.js',
    'jupyter',
  ],
  dependencies: {
    openai: '^3.2.1',
    'pkg-dir': '^7.0.0',
    'ts-node': '^10.9.1',
  },
  pnpm: {
    patchedDependencies: {
      'openai@3.2.1': 'patches/openai@3.2.1.patch',
    },
  },
} as const
